# Generated by Django 5.0 on 2023-12-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_rename_brands_brand'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
