# Generated by Django 4.2.7 on 2023-12-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbuy',
            name='buy_cars',
        ),
        migrations.AddField(
            model_name='carbuy',
            name='buy_cars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
