# Generated by Django 4.2.7 on 2023-12-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_remove_carbuy_buy_cars_carbuy_buy_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbuy',
            name='buy_cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
